### ISSUE TITLE
Currency.getInstance(Locale.getDefault) throws NPE

### ISSUE THREAD

**Issue by darkfrog26** [cquiroz/scala-java-locales#108]
When I attempt to use `Currency.getInstance(Locale.getDefault)` it throws a NPE.  The locale is `en`.

**Comment by cquiroz** [comment]
Are you on version 0.5.x? I haven't used much the `Currency` support

**Comment by darkfrog26** [comment]
On `0.5.5-cldr31`

**Comment by darkfrog26** [comment]
Whoa, this is way worse than I thought. Just calling `NumberFormat.getInstance()` throws a NPE as it calls `Currency.getInstance` internally.

**Comment by cquiroz** [comment]
This should be fixed on 0.6.x
