### ISSUE TITLE
Implement Locale#getISO3Language

### ISSUE THREAD

**Issue by liff** [cquiroz/scala-java-locales#116]
`Locale#getISO3Language` is on the [TODO list](https://github.com/cquiroz/scala-java-locales/blob/08862e46941a976d70140878f2d6812cc8cca977/core/src/main/scala/java/util/Locale.scala#L567). Would be nice to have it.

I would gladly have a go at implementing this but I couldn’t find any obvious source for the data within the CLDR. There is a list available [here](http://loc.gov/standards/iso639-2/ascii_8bits.html). Could/should it perhaps be added as a data source alongside the CLDR?

**Comment by cquiroz** [comment]
Fixed by #115

**Comment by liff** [comment]
#115 is getISO3Country, the getISO3Language is missing as described.

**Comment by cquiroz** [comment]
Ah sorry got confused

**Comment by liff** [comment]
Fixed by #117.
