### ISSUE TITLE
DayofWeek getDisplayname Regression

### ISSUE THREAD

**Issue by mlvn23** [cquiroz/scala-java-locales#152]
I just upgraded to version 0.6.0 and my CI test caught a regression:

        val dow = DayOfWeek.MONDAY
        checkEquals("Mon", dow.getDisplayName(TextStyle.SHORT, Locale.US)) // fails
        checkEquals("Mon", dow.getDisplayName(TextStyle.SHORT, Locale.ENGLISH)) // succeeds

My original test was all using Locale.US and it was passing before. It now fails and it returns an empty string.

**Comment by cquiroz** [comment]
Did you generate a locale db including `US`? You'd do that using `sbt-locales`

**Comment by mlvn23** [comment]
It is not included in the default?

**Comment by mlvn23** [comment]
This is also failing now.

val MONTH_FMT = DateTimeFormatter.ofPattern("MMM yyy")
val zdt = ZDTUTC(2000, 1, 2, 10, 20, 45)
checkEquals("Jan 2000", zdt.format(MONTH_FMT))

**Comment by cquiroz** [comment]
No, ENGLISH as such yes as Scala.js defaults to English but not US, see this example
https://github.com/gemini-hlsw/gemini-locales/

**Comment by mlvn23** [comment]
Ok, thanks. I'll try this.

**Comment by mlvn23** [comment]
Adding the Locale using sbt-locale worked. Thanks!

**Comment by mlvn23** [comment]
BTW, the DateTimeFormatter is still failing. It seems like it is because the default locale is not set. I need to set the default locale first before I could call the DateTimeFormatter.ofPattern, otherwise, it would produce a wrong formatter. I can set (although inconvenient) the default locale on every entry point and every test that I have, but some of my classes uses these as constants in an Object Singleton with complicated dependency. Can we initialize the default locale via sbt-locale in JS?
