### ISSUE TITLE
java.lang.String.toUpperCase(Locale): String

### ISSUE THREAD

**Issue by er1c** [cquiroz/scala-java-locales#197]
Some missing `scala.js` methods that this package can help resolve:

~~java.lang.Character.codePointCount(java.lang.CharSequence,int,int) int~~ https://github.com/scala-js/scala-js/pull/4167
~~java.lang.Character.toTitleCase(int)int~~ https://github.com/scala-js/scala-js/pull/4167
~~java.lang.Character.toLowerCase(int)int~~ https://github.com/scala-js/scala-js/issues/4206
~~java.lang.Character.toUpperCase(int)int~~ https://github.com/scala-js/scala-js/issues/4206
java.lang.String.toUpperCase(java.util.Locale)java.lang.String

## TODO

Do implicit classes help solve this issue? or does it still result in a linking error?

## Research

From: https://unicode.org/Public/UCD/latest/ucd/SpecialCasing.txt

> The data in this file, combined with
> `#` the simple case mappings in UnicodeData.txt, defines the full case mappings
> `#` Lowercase_Mapping (lc), Titlecase_Mapping (tc), and Uppercase_Mapping (uc).

Rererenced file: https://unicode.org/Public/UCD/latest/ucd/UnicodeData.txt

### A single combined file

https://github.com/unicode-org/icu/blob/master/tools/unicode/py/preparseucd.py
https://raw.githubusercontent.com/unicode-org/icu/master/icu4c/source/data/unidata/ppucd.txt

### Some other parsing references

https://docs.rs/ucd-parse/0.1.8/ucd_parse/

https://github.com/jessetane/unicode-database-parser/blob/master/defs.json
https://github.com/jessetane/unicode-database-parser/blob/master/index.js#L8

https://github.com/ekrich/scala-unicode

**Comment by cquiroz** [comment]
This is a bit tricky. At some moment the discussion with the scala.js team about this topic ended up
accepting that there wouldn't be a `toUpperCase(Locale)` method to avoid the `Locale` dependency.
I think you can always do the implicit class trick though it would mean having to do an extra import that does
nothing on the JVM side.
It is probably a good avenue to investigate

**Comment by er1c** [comment]
I've got some prototype code for this approach.  The missing piece right now is the actual Unicode data, still digging into how to best extract and use it.

**Comment by er1c** [comment]
I think all of the case information is in https://unicode.org/Public/UCD/latest/ucd/CaseFolding.txt

**Comment by er1c** [comment]
Pending `java.lang.Character.UnicodeBlock` addition: https://github.com/scala-js/scala-js/pull/4173

**Comment by ekrich** [comment]
I do know that without changing locales the Scala Native mapping exactly matches the JVM. Are they fixed on the JVM or do they use the "SpecialCasing.txt" for certain locales? Right now the Scala.js platform delegates to JS for upper/lowercase transforms. 

What exactly are your goals?

**Comment by er1c** [comment]
@ekrich ultimately the signatures above are ones I need for a library port.  I now think scala-js should own:

```
java.lang.Character.toTitleCase(int)int
java.lang.Character.toLowerCase(int)int
java.lang.Character.toUpperCase(int)int
```

And maybe `scala-java-locales` own:

`java.lang.String.toUpperCase(java.util.Locale)java.lang.String`
`java.lang.String.toLowerCase(java.util.Locale)java.lang.String`

However, based upon a comment from @sjrd the implicits approach I was trying to create a playground around doesn't sound viable.

**Comment by ekrich** [comment]
The trouble starts with the specification, it requires a Locale even for the default - https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#toUpperCase()

For JS? 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLocaleUpperCase

**Comment by sjrd** [comment]
> The trouble starts with the specification, it requires a Locale even for the default - https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#toUpperCase()

Scala.js specifies that the default locale is en-US, always. So we can implement the variant that does not take a Locale argument as if it were for English, which is what we do.

> For JS?
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLocaleUpperCase

Those APIs are not part of the core ECMAScript language spec, which means we cannot use them in the Scala.js core.

**Comment by er1c** [comment]
> > The trouble starts with the specification, it requires a Locale even for the default - [docs.oracle.com/javase/7/docs/api/java/lang/String.html#toUpperCase()](https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#toUpperCase())
> 
> Scala.js specifies that the default locale is en-US, always. So we can implement the variant that does not take a Locale argument as if it were for English, which is what we do.
> 

The caveat here is the codePoint lookups are currently not implemented in scalajs:
* `java.lang.Character.toUpperCase(codePoint: Int)`
* `java.lang.Character.toLowerCase(codePoint: Int)`

**Comment by ekrich** [comment]
I guess in Scala Native we went a little crazy so much of the `Locale` code is stubbed out and essentially ignored anyway. We implemented the `Character.toUpperCase` and `toLowerCase` directly but probably could have used C `toUpper/toLower` instead. This code could be brought to Scala.js if matching the JVM is important and the code tables are not too big. We could also add `toTitleCase` to SN as well.

I am totally in support of offloading both `java.time._` and `java.util.Locale` to third party libs in Scala Native to match Scala.js but it would have to be in the `0.4.0` to `0.5.0` time frame to allow the removal and the third party setup of these packages. We would also have to find homes for all the other pieces in Scala Native that refer to `Locale`.

**Comment by sjrd** [comment]
> The caveat here is the codePoint lookups are currently not implemented in scalajs:
> 
>     * `java.lang.Character.toUpperCase(codePoint: Int)`
>     * `java.lang.Character.toLowerCase(codePoint: Int)`

Those we should be able to easily implement by delegating to the `String` equivalents, after having encoded the code points as UTF-16 code unit(s).

**Comment by er1c** [comment]
> > The caveat here is the codePoint lookups are currently not implemented in scalajs:
> > ```
> > * `java.lang.Character.toUpperCase(codePoint: Int)`
> > * `java.lang.Character.toLowerCase(codePoint: Int)`
> > ```
> 
> Those we should be able to easily implement by delegating to the `String` equivalents, after having encoded the code points as UTF-16 code unit(s).

Oooh, thanks, I created an issue to track here: https://github.com/scala-js/scala-js/issues/4206

**Comment by cquiroz** [comment]
It would certainly be better that native and js used the same logic of splitting classes between their cores and third party libs

**Comment by er1c** [comment]
https://github.com/scala-js/scala-js/pull/4214
