### ISSUE TITLE
CLDR latest not found

### ISSUE THREAD

**Issue by mcallisto** [cquiroz/scala-java-locales#237]
Currently getting
` Error:  Error opening http://unicode.org/Public/cldr/latest/core.zip: java.io.FileNotFoundException: http://unicode.org/Public/cldr/38.1/core.zip
`

Is it something temporary on unicode.org, or there is a misalignment?

**Comment by cquiroz** [comment]
Seems to be not found in that url. I wonder if they changed the naming schema

**Comment by mcallisto** [comment]
At least from [here](http://cldr.unicode.org/index/downloads), it would seem that from release 35 they point to download from github.com instead of unicode.org, don't know if it helps.

**Comment by cquiroz** [comment]
Ok then it needs a change on sbt-locales

**Comment by mcallisto** [comment]
At this line https://github.com/cquiroz/sbt-locales/blob/c3522f6fc2dedc41666af28dac985ab53d7e3c46/sbt-locales/src/main/scala/locales/IOTasks.scala#L21? If you want I can try writing a PR.

**Comment by cquiroz** [comment]
Yes please, it would be nice if it would select the url based on the version

Or is that all old versions are now in GitHub?

**Comment by mcallisto** [comment]
I'll check and propose a solution.

**Comment by mcallisto** [comment]
They seem to be all in GitHub, see https://github.com/unicode-org/cldr/releases

**Comment by mcallisto** [comment]
Proposed a PR, see https://github.com/cquiroz/sbt-locales/pull/78
