### ISSUE TITLE
Version scheme

### ISSUE THREAD

**Issue by Sciss** [cquiroz/scala-java-locales#375]
Hi! What is the version scheme of this library, is it semver or pvp. In other words, is 1.4.0 binary backward compatible with 1.2.1 or not. Perhaps make `ThisBuild / versionScheme` explicit. Thanks.

**Comment by cquiroz** [comment]
The api essentially does not change since its purpose is to follow the signature of the original api.
Still there are changes when bugs are found or platforms (js, native) update

We should perhaps add a versionScheme though. Feel free to send a PR

Thanks

**Comment by armanbilge** [comment]
That's right, this library is unable to make or break binary-compatibility, because the binary API is defined by the JDK. All we can do here is implement it.

Hence, artifacts should _always_ be binary-compatible. I will send a PR to make this explicit.
