### ISSUE TITLE
Support scala native

### ISSUE THREAD

**Issue by cquiroz** [cquiroz/scala-java-locales#38]
At some time in the future

**Comment by sideeffffect** [comment]
Hello, do you plan making a release anytime soon?
The support for Scala Native has been merged to `main` https://github.com/cquiroz/scala-java-locales/pull/307 , right?
/cc @lolgab

**Comment by cquiroz** [comment]
I'm facing some issues with the tests. Many are failing and that will stop publication. Once they are fixed I'll publish

**Comment by cquiroz** [comment]
Could you verify if 1.3.0 works for you. Unfortunately I had to disable the native test so I cannot verify the release works

**Comment by sideeffffect** [comment]
The JARs for both 0.7.0 and 1.3.0 seem to be available for Scala Native 0.4.0, which is a good sign :wink: 
https://repo1.maven.org/maven2/io/github/cquiroz/scala-java-locales_native0.4_2.13/0.7.0/
https://repo1.maven.org/maven2/io/github/cquiroz/scala-java-locales_native0.4_2.13/1.3.0/

But for me to move forward and verify, I'd need also `scala-java-time` which is a dependent of `scala-java-locales`.
Maybe @lolgab has a usecase for mere `scala-java-locales`?

**Comment by lolgab** [comment]
> Maybe @lolgab has a usecase for mere scala-java-locales?

No, I wanted to port `scala-java-time` and I started from `scala-java-locales`. But then I gave up. It is non trivial to port the code generators for scala-java-time to Scala Native since they generate Scala.js specific code.

**Comment by sideeffffect** [comment]
I see, this ticket then depends on https://github.com/cquiroz/sbt-tzdb/issues/144

**Comment by sideeffffect** [comment]
> I see, this ticket then depends on cquiroz/sbt-tzdb#144

Or maybe it doesn't :thinking: 
https://github.com/cquiroz/scala-java-time/pull/346
