### ISSUE TITLE
Version 1.5.2 released against Scala 3.4.1

### ISSUE THREAD

**Issue by mpilquist** [cquiroz/scala-java-locales#490]
Version 1.5.2 of the library was built against Scala 3.4.1 -- https://github.com/cquiroz/scala-java-locales/blob/v1.5.2/build.sbt#L12.

This forces all libraries to upgrade to 3.4.x as well, but the 3.4 series isn't intended for use by library authors. See https://www.scala-lang.org/blog/2024/02/29/scala-3.4.0-and-3.3.3-released.html for details.

Can we release a 1.5.3 that builds against Scala 3.3.3 to fix this?

**Comment by cquiroz** [comment]
Sorry about that, it was an oversight. we'll soon make a release targeting 3.3.3
