### ISSUE TITLE
Publish for 2.12

### ISSUE THREAD

**Issue by soc** [cquiroz/scala-java-locales#60]
Hi @cquiroz,

I want to do a 2.12 release of scala-java-time, could you publish a build of scala-java-locales?

Cheers,

Simon

**Comment by cquiroz** [comment]
Use version 0.3.1-cldr30. It is published as 2.12

**Comment by soc** [comment]
Oh, damn, I didn't see that. :-(
My build file still had 0.3.0 in it.

Thanks!
