### ISSUE TITLE
Build Times?

### ISSUE THREAD

**Issue by schmitch** [cquiroz/scala-java-locales#71]
Actually I tested your library, but then I actually seen that the build times are skyrocketing.
I actually have a really really simple library that compiles really fast.
I tought that making it localized a little bit more would help me make it less dependent on my foreign locales.
However once I added scala-java-locales the build time is really really slow, any idea's why this might happen?

**Comment by cquiroz** [comment]
I haven't seen that on my projects. Are you observing this on the js side or jvm side? What scala version?

the library contains a large amount of data about localization so I can imagine that it takes some extra effort to compile

can you point me to your example project/code?

**Comment by schmitch** [comment]
Well just a simple `Hello World` with ScalaJS 0.6.14 new project with:
```
package com.example

import scala.scalajs.js.JSApp

object Hello extends JSApp {

  def main(): Unit = {
    println("Hello world!")
  }

}
```
plugins.sbt:
```
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.14")
```
build.sbt:
```
name := """scala-js-demo"""

version := "1.0"

scalaVersion := "2.11.8"

lazy val root = project.in(file(".")).enablePlugins(ScalaJSPlugin)

libraryDependencies += "org.scala-js" %%% "scalajs-dom" % "0.9.1"

libraryDependencies += "io.github.cquiroz" %%% "scala-java-locales" % "0.5.0-cldr30"

jsDependencies += RuntimeDOM
```

without locales:
```
$ time sbt clean fastOptJS
[info] Loading global plugins from /Users/schmitch/.sbt/0.13/plugins
[info] Loading project definition from /Users/schmitch/projects/schmitch/scala/scala-js-demo/project
[info] Set current project to scala-js-demo (in build file:/Users/schmitch/projects/schmitch/scala/scala-js-demo/)
[success] Total time: 0 s, completed 28.12.2016 15:49:21
[info] Updating {file:/Users/schmitch/projects/schmitch/scala/scala-js-demo/}root...
[info] Resolving org.eclipse.jetty#jetty-continuation;8.1.16.v20140903 ...
[info] Done updating.
[info] Compiling 1 Scala source to /Users/schmitch/projects/schmitch/scala/scala-js-demo/target/scala-2.11/classes...
[info] Fast optimizing /Users/schmitch/projects/schmitch/scala/scala-js-demo/target/scala-2.11/scala-js-demo-fastopt.js
[success] Total time: 5 s, completed 28.12.2016 15:49:26

real	0m9.285s
user	0m28.063s
sys	0m1.143s
```
I tested multiple runs and the user time is always between 27s and 28s.

After adding:
```
// Install the locale
LocaleRegistry.installLocale(de_DE)

// Now you can use the locale
val dfs = DecimalFormatSymbols.getInstance(Locale.forLanguageTag("de_DE"))
```
Somwhere in the `object Hello` it's more like that:
```
$ time sbt clean fastOptJS
[info] Loading global plugins from /Users/schmitch/.sbt/0.13/plugins
[info] Loading project definition from /Users/schmitch/projects/schmitch/scala/scala-js-demo/project
[info] Set current project to scala-js-demo (in build file:/Users/schmitch/projects/schmitch/scala/scala-js-demo/)
[success] Total time: 0 s, completed 28.12.2016 15:52:02
[info] Updating {file:/Users/schmitch/projects/schmitch/scala/scala-js-demo/}root...
[info] Resolving org.eclipse.jetty#jetty-continuation;8.1.16.v20140903 ...
[info] Done updating.
[info] Compiling 1 Scala source to /Users/schmitch/projects/schmitch/scala/scala-js-demo/target/scala-2.11/classes...
[info] Fast optimizing /Users/schmitch/projects/schmitch/scala/scala-js-demo/target/scala-2.11/scala-js-demo-fastopt.js
[success] Total time: 14 s, completed 28.12.2016 15:52:16

real	0m18.618s
user	1m9.088s
sys	0m3.047s
```

So the fastOptJS time is twice as bad with locales registered?
Actually fullOptJS is even slower. I'm not sure how the data gets loaded but, this is not really good :(

**Comment by cquiroz** [comment]
I've tried all kind of combinations and cannot reproduce this. There is some slowness of course but not the amount you see, perhaps 10 %

In most cases my `sbt clean fastOptJS` takes between 21 and 26 seconds.

I do expect `fullOptJS` to be much slower since the library is designed to produce a small footprint and only bring the minimum amount of code possible

**Comment by cquiroz** [comment]
It seems the update to include the currency data may have created a very large js file. Could you test this with an older version, e.g. 0.3.1:

"com.github.cquiroz" %%% "scala-java-locales" % "0.3.1-cldr30"

**Comment by cquiroz** [comment]
release 0.6.0 should solve this by making currencies optional
