### ISSUE TITLE
How to use installLocale in a cross project?

### ISSUE THREAD

**Issue by migo** [cquiroz/scala-java-locales#73]
I'm trying to use locales in a cross ScalaJs/JVM project. 
However, when I add the dependency to scala-java-locales in the jsSettings only (as recommended in the readme), then LocaleRegistry.installLocale() is not available in the JVM part of the project.
How can install specific locales then?

**Comment by cquiroz** [comment]
Good question. `LocaleRegistry` is of no use on the JVM side, on the other hand it would be a no-op if you do call it on the jvm side. The issue adding it to the jvm part is that the jar includes classes on the `java.util` package and that will create troubles on your application

A short time solution would be to encapsulate your call in some object that is created on the `js` and `jvm` side of your cross project. It would have the same name but different implementations. This is essentially done for the tests at:

https://github.com/cquiroz/scala-java-locales/blob/master/testSuite/js/src/test/scala/testsuite/utils/LocaleTestSetup.scala

And

https://github.com/cquiroz/scala-java-locales/blob/master/testSuite/jvm/src/test/scala/testsuite/utils/LocaleTestSetup.scala



Thinking out loud, we could perhaps have 2 packages. One for the java packages that you only import on the js side and one including `LocaleRegistry` that you can use in either side

**Comment by migo** [comment]
Yes, two packages would perhaps be a good idea.
I didn't know that I could have JS- and JVM-specific classes within one cross-project. I'll see if I can make the short time solution work for me.

**Comment by migo** [comment]
It works, thank you!
I learned that there are "pure" and "full" cross projects and that I have to use a full one for being able to include separate JS and JVM implementations.
