### ISSUE TITLE
Split modules

### ISSUE THREAD

**Issue by cquiroz** [cquiroz/scala-java-locales#76]
We should spilt the modules containing the java API and the data to make it easier to build cross projects

The test module can also be eliminated if there is no interest on merging with the core scala-js library

**Comment by scalway** [comment]
Currently it increases produced .js file significantly. Not sure how much yet (I'll test it in near future). 
Spliting it could help us with this?

**Comment by cquiroz** [comment]
This is already done using sbt-locales

**Comment by scalway** [comment]
WOW... You are fast :)
sbt-locales is for sbt 1.x and i stuck in 0.13.* for now. Hope to jump to it in next version. 
Is somwhere any github project that uses it?

**Comment by cquiroz** [comment]
This is a very simple example
https://github.com/gemini-hlsw/gemini-locales

I'm certainly using it in production
